Hw03 mongodb
Anurov-Prihodko/nodejs-homework-rest-api pull request #2
Opened 2021-11-05 15:24 UTC by Anurov-Prihodko

Проверь пожалуйста

2021-11-05 19:58 UTC, KirillKulakow commented on controllers/contacts/removeContactById.js
> +  console.log(req.params)
удалить

2021-11-05 22:38 UTC, KirillKulakow commented on model/contact.js
> +  { versionKey: false, timestamps: true }
перепроверь у себя работоспособность приложения - так как здесь не хаватает поля с названием коллекции

2021-11-05 22:39 UTC, KirillKulakow commented on validations/contactsValidations.js
> +  favorite: Joi.boolean().required(),
здесь у тебя поле favorite обязательно а в модели базы данных наборот - сделай одинаково

2021-11-05 22:40 UTC, KirillKulakow requested changes
Need a check

2021-11-06 08:53 UTC, Anurov-Prihodko commented on model/contact.js
> +  { versionKey: false, timestamps: true }
Если я делаю как в ДЗ, не корректно отображаются данные: 
Схема: https://drive.google.com/file/d/1LwkHHX28LpUYGQNSkpLqUkpUBzC3S111/view?usp=sharing
Отображение: https://drive.google.com/file/d/1jjlRa-31zvh5vTOgLI64FDKhz_Z9CUAu/view?usp=sharing

2021-11-06 09:04 UTC, Anurov-Prihodko commented on model/contact.js
> +  { versionKey: false, timestamps: true }
Так как сейчас работает хорошо - но если ты будешь настаивать - сделаю как скажешь... но работать будет не корректно.

2021-11-06 09:05 UTC, Anurov-Prihodko commented on controllers/contacts/removeContactById.js
> +  console.log(req.params)
Done

2021-11-06 09:05 UTC, Anurov-Prihodko commented on validations/contactsValidations.js
> +  favorite: Joi.boolean().required(),
Done

2021-11-06 10:05 UTC, KirillKulakow approved these changes

2021-11-06 16:49 UTC, merged