Hw04 auth
Anurov-Prihodko/nodejs-homework-rest-api pull request #3
Opened 2021-11-12 15:35 UTC by Anurov-Prihodko

Check please

2021-11-12 22:34 UTC, KirillKulakow commented on middlewares/authentication.js
> +    const [bearer, token] = req.headers.authorization.split(' ')
вот здесь у тебя будет необработанная ошибка, если не будет хедера вообще

2021-11-12 22:47 UTC, KirillKulakow commented on controllers/contacts/getAll.js
> +  const skip = (page - 1) * limit
если я явно не указываю page и лимит выводится 500 ошибка
или поставь дефолтные или поставь проверку на пустые данные

2021-11-12 22:49 UTC, KirillKulakow commented on controllers/contacts/getAll.js
> +  const skip = (page - 1) * limit
и лучше не использовать какие либо константы (я про 1) в расчетах - можно написать page * limit - limit

2021-11-12 22:53 UTC, KirillKulakow commented on model/contact.js
>        default: false,
обычно ставится или дефолт или обязательное поле
рекомендую удалить обязательное поле

2021-11-13 11:10 UTC, KirillKulakow requested changes
Need Fix

2021-11-13 15:50 UTC, Anurov-Prihodko commented on controllers/contacts/getAll.js
> +  const skip = (page - 1) * limit
Если пишу  const skip = (page - (limit - limit)) * limit или делаю отдельную переменную: const one = page - page => не выводит данные, а с единицей работает нормально.

2021-11-13 15:52 UTC, Anurov-Prihodko commented on model/contact.js
>        default: false,
Done

2021-11-13 15:52 UTC, Anurov-Prihodko commented on middlewares/authentication.js
> +    const [bearer, token] = req.headers.authorization.split(' ')
Done

2021-11-13 16:38 UTC, Anurov-Prihodko commented on controllers/contacts/getAll.js
> +  const skip = (page - 1) * limit
Привел к числу +limit и заработало как нужно ))

2021-11-13 17:47 UTC, KirillKulakow commented on controllers/contacts/getAll.js
> +  const { page = 1, limit = 2 } = req.query
На бал не влияет, но было бы неплохо сделать небольшую проверку на эти два параметра (чтобы они точно были числом) Поесть если page или limit не число выдать ошибку BadRequest

2021-11-13 17:48 UTC, KirillKulakow approved these changes

2021-11-13 19:15 UTC, merged