Hw05 avatars
Anurov-Prihodko/nodejs-homework-rest-api pull request #4
Opened 2021-11-18 14:42 UTC by Anurov-Prihodko

Проверь, пожалуйста

2021-11-19 19:27 UTC, KirillKulakow commented on controllers/users/updateAvatar.js
> +  if (!req.user) {
зачем эта проверка если у тебя есть мидлвара для аутентификация?

2021-11-20 11:24 UTC, KirillKulakow commented on controllers/users/updateAvatar.js
> +    await fs.rename(tmpUpload, resultUpload)
fs.rename не создаст новую директорию для определенного юзера - будет ошибка

2021-11-20 11:29 UTC, KirillKulakow commented on controllers/users/signup.js
> +  const avatar = gravatar.url(email, { s: '250' })
незнаю заметил ты или нет, но у тебя создаются ломаные пути к картинкам
пример - "//www.gravatar.com/avatar/febb8ac1667616256d3dcbc5feada22d?s=250"
нужно поправить - если не поймешь как, напишешь

2021-11-20 11:30 UTC, KirillKulakow requested changes
Need fix

2021-11-20 11:32 UTC, KirillKulakow commented on middlewares/upload.js
> +  filename: (req, file, cb) => {
было бы неплохо еще делать проверку на MIME Type файла, но это по желанию

2021-11-20 13:59 UTC, Anurov-Prihodko commented on controllers/users/updateAvatar.js
> +    await fs.rename(tmpUpload, resultUpload)
У меня новая директория создавалась когда регистрируется пользователь (папка с email юзера) - и туда попадали фото, ошибки не было. Я убрал email с пути. теперь они валятся все в одну папку.

2021-11-20 14:19 UTC, Anurov-Prihodko commented on controllers/users/signup.js
> +  const avatar = gravatar.url(email, { s: '250' })
добавил протокол https

2021-11-20 14:20 UTC, Anurov-Prihodko commented on controllers/users/updateAvatar.js
> +  if (!req.user) {
Удалил

2021-11-20 14:52 UTC, Anurov-Prihodko commented on middlewares/upload.js
> +  filename: (req, file, cb) => {
Добавил

2021-11-20 15:04 UTC, KirillKulakow commented on controllers/users/updateAvatar.js
> +    await fs.rename(tmpUpload, resultUpload)
я понял почему - у меня старый юзер был в монге - поэтому для него и не было директории

2021-11-20 15:05 UTC, KirillKulakow approved these changes

2021-11-20 16:49 UTC, merged